In [1]:
import numpy as np
#Importing numpy Library 

In [2]:
# 1) 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type
arr = np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [3]:
# 2) Give numpy array check if its data type is float
arr1 = np.array([1.5, 2.6, 3.7])
for x in arr:
    if np.dtype(x) == float:
        print(x,"Is Float")



In [4]:
# 3) 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers
## We can mention initially made array "arr " and convert its integer elements into a complex number
arr.astype("complex128")

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [5]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
print(arr.dtype)
# Converting the data type of arr from int to float
arr = arr.astype("float64") 
print(arr.dtype) # the data type of the array will show as float at this stage 

int64
float64


In [6]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
# Lets creaate  some array of random flaot numbers 
arr2 = np.random.uniform(1,2,size = 5) # This array has 5 random flaot numbers between 1 and 2
print(arr2) # This will return the elements of the array with more than Two decimal palces 
# Lets reduce the  after ecimal places of the elements to two decimal places 
arr2 = np.round(arr2,2)
arr2 # This will return the elements with just two decimal places 

[1.78319123 1.46475546 1.43977259 1.39545307 1.53793959]


array([1.78, 1.46, 1.44, 1.4 , 1.54])

In [7]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
import numpy as np

# Create a list and convert it to a NumPy array
List = [1, 2, 3, 4, 5]
array = np.array(List)

# Define the function to return attributes of the NumPy array
def attri_arr(array):
    shape = array.shape  # Get the shape of the array
    size = array.size    # Get the total number of elements
    ndim = array.ndim    # Get the number of dimensions
    return shape, size, ndim

# Call the function and print the results
shape, size, ndim = attri_arr(array)
print("Shape:", shape)
print("Size:", size)
print("Number of dimensions:", ndim)


Shape: (5,)
Size: 5
Number of dimensions: 1


In [8]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
def array_dimension (array):
    ndim = array.ndim
    return ndim

print(array_dimension(array))


3


In [9]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
def item_size(array):
    size = array.size
    return size

print(item_size(array))


9


In [10]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
def array_strides(array):
    strides = array.strides
    return strides

print(array_strides(array))


(72, 24, 8)


In [11]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.


array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
def array_strides(array):
    shape = array.shape
    strides = array.strides
    return shape,strides

print(array_strides(array))


((1, 3, 3), (72, 24, 8))


In [6]:
# 11 Create a function create_array that takes an integer n as an input and returns a Numpy array of Zeroes with n elemenets 

def create_array():
    n = int(input("Enter the value of n"))
    zeroes_array = np.zeros(n)
    return zeroes_array
result = create_array()
print(result)

Enter the value of n 2


[0. 0.]


In [ ]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 
# 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows, col,n):
    rows = int(input("Enter the values for rows: "))
    col = int(input("Enter the value for columns: "))
    n = rows*col    # Because the number of rows and colums should be the factors of the number of elemnts in the final array
    ones_matrix = np.ones(n)
    ones_matrix = ones_matrix.reshape(rows,col)
    return ones_matrix,n

ones = create_ones_matrix(2,3,n)
print(ones)
    
    


In [ ]:
""" 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`. """

def generate_range_array(start,stop,step):
    range_array = np.arange(start,stop,step)
    return range_array

print(generate_range_array(2,10,1))

In [ ]:
""" 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive).
"""
def generate_linear_space(start,stop,num):
    lin_array = np.linspace(start,stop,num)
    return lin_array

print(generate_linear_space(2,6,50))
    

In [ ]:
""" 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye`. """



def create_identity_matrix():
    n = int(input("Enter the size of the identity matrix: "))  # Take user input inside the function
    identity_matrix = np.eye(n)  # Create an identity matrix of size n x n
    return identity_matrix

result = create_identity_matrix()
print(result)


In [ ]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def arr_create():
    numbers = (input("Enter the numbers here : "))
    List = list(numbers)
    print(List)
    for x in List:
        x = int(x)
        print(x, type(x))
    arr1 =np.array(List)
    return arr1

print(arr_create(),type(arr1))

In [ ]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
original_array = np.random.uniform(0,10,10) # Craete an array
view_original = original_array.view()  # create another array with the same elements 
if original_array is view_original: # Checks if the both the objects are same or not
    print("True")
else:
    print("False")
if np.shares_memory(original_array,view_original):# Checks if both the bojects have smae data or not
    print("True")
else:
    print("False")
    


In [ ]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concat_array():
    List1 = list(input("List1: "))
    List2 = list(input("List2: "))
    arra1 = np.array(List1)
    arra2 = np.array(List2)
    reshape= input(f"Want to reshape: arra1 {arra1.shape}  and arra2 {arra2.shape}")
    if reshape == "yes":
        rows1 = int(input("Number of rows1: "))
        columns1 = int(input("Number of columns1: "))
        rows2 = int(input("Number of rows2: "))
        columns2 = int(input("Number of columns2"))
        if arra1.size== rows1* columns1 and arra2.size==rows2*columns2:
            arra1 = arra1.reshape(rows1,columns1)
            arra2 = arra2.reshape(rows2,columns2)
    shape1 = list(arra1.shape)
    shape2 = list(arra2.shape)
    if len(shape1)>1 and len(shape2)>1:
        axis = int(input("axis: "))
        concate = np.concat([arra1,arra2],axis)
    else:
        concate = np.concat([arra1,arra2],axis=0)

    return concate
    
    
concat_array()
    

In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

# Create two arrays with different shapes
arr1 = np.array([[1, 2], [3, 4]])  # Shape: (2, 2)
arr2 = np.array([[5], [6]])        # Shape: (2, 1)

# Concatenate the arrays horizontally (axis=1)
result = np.concatenate((arr1, arr2), axis=1)

print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Concatenated Array:")
print(result)


In [ ]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def stack_arrays_vertically(arrays_list):
    return np.vstack(arrays_list) # Stacks veritcally

# Example usage
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

arrays_list = [arr1, arr2, arr3]
result = stack_arrays_vertically(arrays_list)
print(result)


In [ ]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size
def create_array_in_range(start, end, step):
    # Use np.arange to generate the array within the specified range and step size
    return np.arange(start, end + 1, step)


start = int(input("Enter the start value: "))  
end = int(input("Enter the end value: "))      
step = int(input("Enter the step size: "))     

# Call the function and store the result
result = create_array_in_range(start, end, step)

# Print the resulting NumPy array
print(result)


In [13]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def generate_spaced_values():
    values = np.linspace(0, 1, 10)
    return values


result = generate_spaced_values()
print(result)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [14]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def generate_log_spaced_values():
    values = np.logspace(0, 3, 5)
    return values


result = generate_log_spaced_values()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [9]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100
import pandas as pd

def create_random_dataframe():
    # Generate a 5x3 NumPy arry with random intgers between 1 and 100
    random_array = np.random.randint(1, 101, size=(5, 3))
    # Convert the NumPy aray to a Pandas DataFrame
    df = pd.DataFrame(random_array, columns=['Colum1', 'Colun2', 'Colu3'])
    # Assign colunm names as Column1, Column2, and Column3
    return df


result = create_random_dataframe()
print(result)


   Colum1  Colun2  Colu3
0      92      78     80
1      89      64     90
2      68      49     58
3      78      14     47
4      30      36     75


In [16]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas 
def create_random_dataframe():
    # Generate a 5x3 NumPy arry with random intgers between 1 and 100
    random_array = np.random.randint(1, 101, size=(5, 3))
    # Convert the NumPy aray to a Pandas DataFrame
    df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])
    # Assign colunm names as Column1, Column2, and Column3
    return df

# Call the funtion and display the DataFrame
result = create_random_dataframe()
print(result)

   Column1  Column2  Column3
0        3       85       68
1       96       29       37
2       95       91       74
3       20       14        3
4       58       86       87


In [17]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

# Accessing the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)

The 3rd element is: 30


In [19]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Accessing the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)

The element at index (1, 2) is: 6


In [20]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Using boolean indexing to extract elements greater than 5
elements_greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", elements_greater_than_5)

Elements greater than 5: [ 8 10  7]


In [21]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing from index 2 to 5 (inclusive)
sliced_elements = arr[2:6]

print("Elements from index 2 to 5:", sliced_elements)

Elements from index 2 to 5: [3 4 5 6]


In [22]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slicing to extract the sub-array
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:")
print(sub_array)

Extracted sub-array:
[[2 3]
 [5 6]]


In [23]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Indices array (row, column)
indices = np.array([[0, 1], [1, 2], [2, 0]])

# Extract elements using the indices
extracted_elements = arr_2d[indices[:, 0], indices[:, 1]]

print("Extracted elements in specific order:")
print(extracted_elements)

Extracted elements in specific order:
[20 60 70]


In [24]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_elements(arr, threshold):
    filtered_arr = arr[arr > threshold]
    return filtered_arr


arr = np.array([1, 5, 8, 12, 3, 7, 9])
threshold = 6
filtered_result = filter_elements(arr, threshold)

print("Filtered elements greater than threshold:")
print(filtered_result)

Filtered elements greater than threshold:
[ 8 12  7  9]


In [8]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_elements_3d(arr, idx1, idx2, idx3):
    extracted_elements = arr[idx1, idx2, idx3]
    return extracted_elements

# Creating a 3D array of shape (4, 4, 4)
arr_3d = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]],
                   
                   [[17, 18, 19, 20],
                    [21, 22, 23, 24],
                    [25, 26, 27, 28],
                    [29, 30, 31, 32]],
                   
                   [[33, 34, 35, 36],
                    [37, 38, 39, 40],
                    [41, 42, 43, 44],
                    [45, 46, 47, 48]],
                   
                   [[49, 50, 51, 52],
                    [53, 54, 55, 56],
                    [57, 58, 59, 60],
                    [61, 62, 63, 64]]])

# Indices for ech dimension (example)
idx1 = np.array([0, 1, 2])  
idx2 = np.array([0, 2, 3])  
idx3 = np.array([1, 3, 0])  

# Extrct ellements using the indices
result = extract_elements_3d(arr_3d, idx1, idx2, idx3)

print("Extraced elemnts:", result)

Extraced elemnts: [ 2 28 45]


In [10]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def filter_elements(arr, condition1, condition2):
    filtered_elements = arr[condition1 & condition2]
    return filtered_elements

# Creating a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])


condition1 = arr > 30
condition2 = arr < 80

result = filter_elements(arr, condition1, condition2)
 mml.;
print("Filtered elements:", result)

IndentationError: unexpected indent (3556898596.py, line 14)

In [11]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_elements_2d(arr, row_indices, col_indices):
    elements = arr[row_indices, col_indices]
    return elements

# Example usage:
# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])  
col_indices = np.array([0, 1, 2])  

result = extract_elements_2d(arr_2d, row_indices, col_indices)

print("Extracted elements:", result)

Extracted elements: [1 5 9]


In [28]:
#  36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting
def add_scalar_to_array(arr, scalar):
    result = arr + scalar
    return result

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

scalar_value = 5

result = add_scalar_to_array(arr, scalar_value)

print("Original array:\n", arr)
print("Array after adding scalar value:\n", result)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding scalar value:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [12]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
def multiply_rows_by_elements(arr1, arr2):
    result = arr1 * arr2
    return result

# arr1 has shape (1, 3) and arr2 has shape (3, 4)
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[4, 5, 6, 7],  # Shape (3, 4)
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = multiply_rows_by_elements(arr1, arr2)

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result after multiplication:\n", result)

ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

In [31]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
def add_array_to_rows(arr1, arr2):
    # Reshape arr1 to match the dimensions of arr2 for broadcasting
    arr1 = arr1.T  # Transpose arr1 to shape (4, 1)
    
    # Add arr1 to each row of arr2 using broadcasting
    result = arr2 + arr1
    return result

# Example usage:
# arr1 has shape (1, 4) and arr2 has shape (4, 3)
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],      # Shape (4, 3)
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

# Add arr1 to each row of arr2 using broadcasting
result = add_array_to_rows(arr1, arr2)

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result after addition:\n", result)

arr1:
 [[1 2 3 4]]
arr2:
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]
Result after addition:
 [[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [32]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
def add_arrays_using_broadcasting(arr1, arr2):
    result = arr1 + arr2
    return result

# Example usage:
# arr1 has shape (3, 1) and arr2 has shape (1, 3)
arr1 = np.array([[1], [2], [3]])  
arr2 = np.array([[4, 5, 6]])     

# Add the arrays using broadcasting
result = add_arrays_using_broadcasting(arr1, arr2)

print("arr1:\n", arr1)
print("arr2:\n", arr2)
print("Result after addition:\n", result)

arr1:
 [[1]
 [2]
 [3]]
arr2:
 [[4 5 6]]
Result after addition:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [13]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
def multiply_arrays_using_broadcasting(arr1, arr2):
    arr2_reshaped = np.tile(arr2, (1, 3))  # Repeat arr2 along the columns (2, 3)
    
    # Perform element-wise multiplication
    result = arr1 * arr2_reshaped
    return result

# Example usage:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  
arr2 = np.array([[7, 8]])                 

# Perform multiplication using broadcasting after reshaping arr2
result = multiply_arrays_using_broadcasting(arr1, arr2)

print("arr1:\n", arr1)
print("arr2 reshaped:\n", np.tile(arr2, (1, 3)))  # Showing reshaped arr2
print("Result after multiplication:\n", result)

ValueError: operands could not be broadcast together with shapes (2,3) (1,6) 

In [14]:
# 41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Calculate column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_wise_mean)

Column-wise mean: [2.5 3.5 4.5]


In [36]:
# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

row_max = np.max(arr, axis=1)

print("Maximum value in each row:", row_max)

Maximum value in each row: [3 6]


In [15]:
# 43. For the given array, find indices of maximum value in each column

arr = np.array([[1, 2, 3], [4, 5, 6]])

col_max_indices = np.argmax(arr, axis=0)

print("Indices of maximum values in each column:", col_max_indices)

Indices of maximum values in each column: [1 1 1]


In [16]:
# 44. For the given array, apply custom function to calculate moving sum along rows
def moving_sum(arr, window_size):
    return np.array([np.convolve(row, np.ones(window_size), mode='valid') for row in arr])

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Apply custom moving sum function with a window size of 2
result = moving_sum(arr, window_size=2)

print("Moving sum along rows:\n", result)

Moving sum along rows:
 [[ 3.  5.]
 [ 9. 11.]]


In [17]:
# 45. In the given array, check if all elements in each column are even.
# Given array
arr = np.array([[2, 4, 6], [3, 5, 7]])

# Check if each element is even
even_check = (arr % 2 == 0)

# Check if all elements in each column are even
result = np.all(even_check, axis=0)

print("Are all elements in each column even?", result)

Are all elements in each column even? [False False False]


In [18]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

m, n = 2, 3

# Reshape the array
reshaped_array = original_array.reshape(m, n)

print("Reshaped Array:")
print(reshaped_array)

Reshaped Array:
[[1 2 3]
 [4 5 6]]


In [19]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
def flatten_matrix(matrix):
    return matrix.flatten()

# Input matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Call the function to flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Flattened Array:")
print(flattened_array)


Flattened Array:
[1 2 3 4 5 6]


In [20]:
# 48. Write a function that concatenates two given arrays along a specified axis

def concatenate_arrays(array1, array2, axis):
    # Check if arrays can be concatenated along the specified axis
    if axis == 0 and array1.shape[1] == array2.shape[1]:
        return np.concatenate((array1, array2), axis=axis)
    elif axis == 1 and array1.shape[0] == array2.shape[0]:
        return np.concatenate((array1, array2), axis=axis)
    else:
        print("Shape mismatch: Cannot concatenate along the specified axis.")
        return None

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array = concatenate_arrays(array1, array2, axis=0)

print("Concatenated Array along axis 0:")
print(concatenated_array)

concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)

print("Concatenated Array along axis 1:")
print(concatenated_array_axis1)

Concatenated Array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated Array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
# Function to split an array into multiple sub-arrays along a specified axis
def split_array(array, axis, num_splits):
    if axis == 0 and array.shape[0] % num_splits == 0:
        return np.array_split(array, num_splits, axis=axis)
    elif axis == 1 and array.shape[1] % num_splits == 0:
        return np.array_split(array, num_splits, axis=axis)
    else:
        print("Shape mismatch: Cannot split along the specified axis.")
        return None

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split the array along axis 0 (vertically) into 3 sub-arrays
split_array_axis0 = split_array(original_array, axis=0, num_splits=3)
print("Array split along axis 0:")
for sub_array in split_array_axis0:
    print(sub_array)

# Split the array along axis 1 (horizontally) into 3 sub-arrays
split_array_axis1 = split_array(original_array, axis=1, num_splits=3)
print("\nArray split along axis 1:")
for sub_array in split_array_axis1:
    print(sub_array)

Array split along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Array split along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [22]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    for idx, value in zip(indices_to_insert, values_to_insert):
        array = np.insert(array, idx, value)
    
    # Delete elements at specified indices
    for idx in sorted(indices_to_delete, reverse=True):  # Deletin\g from highest index to avoid shifting
        array = np.delete(array, idx)
    
    return array

# Given original array and specified innndices
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]  
values_to_insert = [10, 11] 
indices_to_delete = [1, 3] 

modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Modified Array:", modified_array)

Modified Array: [ 1 10 11  4  5]


In [23]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
# Function to perform element-wise addition of two arrays
def elementwise_addition():
    arr1 = np.random.randint(1, 20, size=(3, 3))  # Example shape (3, 3)
    print("Array 1 (random integers):")
    print(arr1)
    
    # Createee an array arr2 with integers from 1 to 10
    arr2 = np.arange(1, 10).reshape(3, 3)  # Example shape (3, 3)
    print("\nArray 2 (integers from 1 to 10):")
    print(arr2)
    
    # Perform element-wise addition
    result = arr1 + arr2
    return result

result = elementwise_addition()
print("\nResult of elementwise addition:")
print(result)


Array 1 (random integers):
[[ 3 12  1]
 [18  2 14]
 [ 5 12 12]]

Array 2 (integers from 1 to 10):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Result of elementwise addition:
[[ 4 14  4]
 [22  7 20]
 [12 20 21]]


In [48]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
# Function to subtract arr2 from arr1 element-wise
def elementwise_subtraction():
    # Create arr1 with sequential integers from 10 to 1
    arr1 = np.arange(10, 0, -1)  # Sequential integers from 10 to 1
    print("Array 1 (sequential integers from 10 to 1):")
    print(arr1)
    
    # Create arr2 with integers from 1 to 10
    arr2 = np.arange(1, 11)  # Integers from 1 to 10
    print("\nArray 2 (integers from 1 to 10):")
    print(arr2)
    
    # Perform element-wise subtraction (arr1 - arr2)
    result = arr1 - arr2
    return result

# Call the function and print the result
result = elementwise_subtraction()
print("\nResult of element-wise subtraction:")
print(result)

Array 1 (sequential integers from 10 to 1):
[10  9  8  7  6  5  4  3  2  1]

Array 2 (integers from 1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [24]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
# Function to multiply arr1 and arr2 element-wise
def elementwise_multiplication():
    arr1 = np.random.randint(1, 10, size=5)  # Random integers between 1 and 10
    print("Array 1 (random integers):")
    print(arr1)
    
    # Create arr2 with integers from 1 to 5
    arr2 = np.arange(1, 6)  # Integers from 1 to 5
    print("\nArray 2 (integers from 1 to 5):")
    print(arr2)
    
    # Perform elementwise multiplication (arr1 * arr2)
    result = arr1 * arr2
    return result

result = elementwise_multiplication()
print("\nResult of element-wise multiplication:")
print(result)

Array 1 (random integers):
[5 4 7 7 3]

Array 2 (integers from 1 to 5):
[1 2 3 4 5]

Result of element-wise multiplication:
[ 5  8 21 28 15]


In [50]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
# Function to divide arr1 by arr2 element-wise
def elementwise_division():
    # Create arr1 with even integers from 2 to 10
    arr1 = np.arange(2, 11, 2)  # Even integers between 2 and 10
    print("Array 1 (even integers from 2 to 10):")
    print(arr1)
    
    # Create arr2 with integers from 1 to 5
    arr2 = np.arange(1, 6)  # Integers from 1 to 5
    print("\nArray 2 (integers from 1 to 5):")
    print(arr2)
    
    # Perform element-wise division (arr1 / arr2)
    result = arr1 / arr2
    return result

# Call the function and print the result
result = elementwise_division()
print("\nResult of element-wise division:")
print(result)

Array 1 (even integers from 2 to 10):
[ 2  4  6  8 10]

Array 2 (integers from 1 to 5):
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [25]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
# Function to divide arr1 by arr2 element-wise
def elementwise_division():
    arr1 = np.arange(2, 11, 2) 
    print("Array 1 (even integers from 2 to 10):")
    print(arr1)
    
    arr2 = np.arange(1, 6)  # Integers from 1 to 5
    print("\nArray 2 (integers from 1 to 5):")
    print(arr2)
    
    result = arr1 / arr2
    return result

result = elementwise_division()
print("\nResult of element-wise division:")
print(result)

Array 1 (even integers from 2 to 10):
[ 2  4  6  8 10]

Array 2 (integers from 1 to 5):
[1 2 3 4 5]

Result of element-wise division:
[2. 2. 2. 2. 2.]


In [52]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# Function to perform exponentiation of arr1 raised to the power of arr2 element-wise
def elementwise_exponentiation():
    # Create arr1 with integers from 1 to 5
    arr1 = np.array([1, 2, 3, 4, 5])
    print("Array 1 (integers from 1 to 5):")
    print(arr1)
    
    # Create arr2 with the same numbers reversed
    arr2 = np.array([5, 4, 3, 2, 1])
    print("\nArray 2 (integers from 5 to 1):")
    print(arr2)
    
    # Perform element-wise exponentiation (arr1 ** arr2)
    result = arr1 ** arr2
    return result

result = elementwise_exponentiation()
print("\nResult of element-wise exponentiation:")
print(result)

Array 1 (integers from 1 to 5):
[1 2 3 4 5]

Array 2 (integers from 5 to 1):
[5 4 3 2 1]

Result of element-wise exponentiation:
[ 1 16 27 16  5]


In [26]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

def extract_uppercase(arr):
    uppercase_chars = np.char.extract(arr, r'[A-Z]') 
    # Flatten the result and remove empty entries
    return ''.join(uppercase_chars[~np.char.eq(uppercase_chars, '')])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

result = extract_uppercase(arr)
print(f"Extracted uppercase characters: {result}")

AttributeError: module 'numpy.char' has no attribute 'extract'

In [27]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Replace 'apple' with 'fruit' in the array
result = replace_substring(arr, 'apple', 'fruit')
print(f"Replaced array: {result}")

Replaced array: ['fruit' 'banana' 'grape' 'pinefruit']


In [28]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
# Function to concatenate strings in two NumPy arrays element-wise
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate the strings from both arrays
result = concatenate_strings(arr1, arr2)
print(f"Concatenated array: {result}")

Concatenated array: ['HelloOpen' 'WorldAI']


In [29]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

# Function to find the length of the longest string in a NumPy array
def longest_string_length(arr):
    string_lengths = np.vectorize(len)(arr)
    return np.max(string_lengths)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = longest_string_length(arr)
print(f"The length of the longest string is: {result}")

The length of the longest string is: 9


In [30]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")

Mean: 442.84
Median: 431.0
Variance: 83517.1544
Standard Deviation: 288.99334663621585


In [31]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np

dataset = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")

25th Percentile: 15.25
75th Percentile: 68.0


In [62]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

# Define two arrays representing two sets of variables
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient between arr1 and arr2
correlation_matrix = np.corrcoef(arr1, arr2)

# Print the correlation matrix
print(f"Correlation Coefficient Matrix:\n{correlation_matrix}")

# Extract the correlation coefficient between arr1 and arr2
correlation = correlation_matrix[0, 1]
print(f"Correlation Coefficient between arr1 and arr2: {correlation}")

Correlation Coefficient Matrix:
[[ 1. -1.]
 [-1.  1.]]
Correlation Coefficient between arr1 and arr2: -0.9999999999999999


In [32]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using the dot function
result = np.dot(matrix1, matrix2)

print(f"Result of Matrix Multiplication:\n{result}")

Result of Matrix Multiplication:
[[19 22]
 [43 50]]


In [33]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles
# Create an array of 50 random integers between 10 and 1000
arr = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(arr, 10)
median = np.percentile(arr, 50)
percentile_90 = np.percentile(arr, 90)

# Calculate the first and third quartiles
first_quartile = np.percentile(arr, 25)
third_quartile = np.percentile(arr, 75)

print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {median}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (25th Percentile): {first_quartile}")
print(f"Third Quartile (75th Percentile): {third_quartile}")

10th Percentile: 162.0
50th Percentile (Median): 435.5
90th Percentile: 880.6
First Quartile (25th Percentile): 261.25
Third Quartile (75th Percentile): 738.75


In [35]:
# 66. Create a NumPy array of integers and find the index of a specific element.
# Create a NumPy array of integers
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Specify the element whose index you want to find
element = 40

# Find the index of the element
index = np.where(arr == element)

# Check if the element is found
if index[0].size > 0:
    print(f"The index of element {element} is {index[0][0]}.")
else:
    print(f"The elment {element} is not found in the array.")

The index of element 40 is 3.


In [38]:
# 67. Generate a random NumPy array and sort it in ascending order.

# Generate a random NumPy array with 10 integers between 1 and 100
random_array = np.random.randint(1, 101, size=10)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Original array:", random_array) 
print("Sorted array:", sorted_array)  

Original array: [35 28 71 40 42  3 71  5 63 26]
Sorted array: [ 3  5 26 28 35 40 42 63 71 71]


In [37]:
# 68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_elements = arr[arr > 20]

print("Original array:", arr)  # Array before filtering
print("Filtered elements (greater than 20):", filtered_elements)  # Elements >20

Original array: [12 25  6 42  8 30]
Filtered elements (greater than 20): [25 42 30]


In [39]:
# 69. Filter elements which are divisible by 3 from a given NumPy array
# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
divisible_by_3 = arr[arr % 3 == 0]

print("Original array:", arr)  
print("Elements divisible by 3:", divisible_by_3)  

Original array: [ 1  5  8 12 15]
Elements divisible by 3: [12 15]


In [40]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements where 20 ≤ element ≤ 40
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

print("Original array:", arr)  # Original array
print("Elements between 20 and 40 (inclusive):", filtered_elements)  



Original array: [10 20 30 40 50]
Elements between 20 and 40 (inclusive): [20 30 40]


In [10]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.


arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

# Print the byte order
print("Byte order of the array:", byte_order)


Byte order of the array: =


In [41]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(inplace=True)

print("Array after byte swapping:", arr)

Array after byte swapping: [16777216 33554432 50331648]


In [42]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder()
arr = np.array([1, 2, 3], dtype=np.int32)

# Create a new array with swapped byte order
swapped_arr = arr.newbyteorder()

# Print the original and the swapped arrays
print("Original array:", arr)
print("Swapped byte order array:", swapped_arr)

AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [45]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int23)

# Swap byte order conditionally based on system endianness
if arr.dtype.byteorder == '=':  # check for native byteorder
    swapped_arr = arr.newbyotder()  # incorrect method name
else:
    swapped_arr = arr.newbyteorder('S')  # swapping the byte order

print("Original array:", arr)
print("Swapped array:", swapped_arr)

AttributeError: 'numpy.ndarray' object has no attribute 'newbyotder'

In [47]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
# arr = np.array([1, 2, 3], dtype=np.int32)
import sys

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check system endianness
system_endianness = sys.byteorder  # 'little' or 'big'

# Swap byte order conditionally based on the system's endianness
if system_endianness == 'little':
    # If system is little-endian, swap the byte order
    swapped_arr = arr.newbyteorder('>')
else:
    # If system is big-endian, no need to swap
    swapped_arr = arr

# Print the original and swapped arrays
print("Original array:", arr)
print("Conditionally swapped byte order array:", swapped_arr)

AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [48]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
# Create a NumPy array arr1 with values from 1 to 10
arr1 = np.arange(1, 11)

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("arr1:", arr1)
print("copy_arr:", copy_arr)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [49]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. 
# Modify an element in `view_slice` and observe if it changes the original `matrix`.
matrix = np.random.randint(1, 10, size=(3, 3))

# Extract a slice view from the matrix
view_slice = matrix[0:2, 0:2]

view_slice[0, 0] = 100

# Observe if modifying view_slice changes the original matrix
print("Original matrix:")
print(matrix)
print("\nModified view_slice:")
print(view_slice)

Original matrix:
[[100   1   9]
 [  5   9   9]
 [  9   5   7]]

Modified view_slice:
[[100   1]
 [  5   9]]


In [50]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`
# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, 0:2]

# Broadcast the addition of 5 to view_b
view_b += 5

# Check if modifying view_b alters the original array_a
print("Original array_a:")
print(array_a)
print("\nModified view_b:")
print(view_b)

Original array_a:
[[ 1  2  3]
 [ 9 10  6]
 [12 13  9]
 [10 11 12]]

Modified view_b:
[[ 9 10]
 [12 13]]


In [52]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
# reflects changes in the original `orig_array`.


orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view reshaped_view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Modify an element in reshaped_view
reshaped_view[0, 0] = 100

# Check if modifying reshaped_view affects orig_array
print("Original orig_array:")
print(orig_array)

print("\nModified reshaped_view:")
print(reshaped_view)


Original orig_array:
[[100   2   3   4]
 [  5   6   7   8]]

Modified reshaped_view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [30]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of lements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
# Create a NumPy array 'data' of shape (3, 4) with random integers between 1 and 10
data = np.random.randint(1, 11, size=(3, 4))

# Extract a copy of elements greater than 5 from 'data'
data_copy = data[data > 5].copy()

# Modify an element in 'data_copy'
data_copy[0] = 999

# Print the original 'data' and the modified 'data_copy'
print("Original data:")
print(data)

print("\nModified data_copy:")
print(data_copy)

Original data:
[[ 5  3  9  6]
 [ 1  5 10  5]
 [10  7  6  5]]

Modified data_copy:
[999   6  10  10   7   6]


In [32]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
# Create two matrices A and B of shape (3, 3) containing random integers between 1 and 10
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

# Perform element-wise addition
addition_result = A + B

# Perform element-wise subtraction
subtraction_result = A - B

# Print the matrices and results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition of A and B:")
print(addition_result)

print("\nSubtraction of A and B:")
print(subtraction_result)

Matrix A:
[[ 2 10  9]
 [ 8  1  1]
 [ 6  2  2]]

Matrix B:
[[ 4  7  3]
 [10  1  7]
 [ 6  3  4]]

Addition of A and B:
[[ 6 17 12]
 [18  2  8]
 [12  5  6]]

Subtraction of A and B:
[[-2  3  6]
 [-2  0 -6]
 [ 0 -1 -2]]


In [33]:
# Generate matrix C (3x2) with random integers
C = np.random.randint(1, 11, size=(3, 2))

# Generate matrix D (2x4) with random integers
D = np.random.randint(1, 11, size=(2, 4))

# Perform matrix multiplication
result = np.dot(C, D)

# Print the matrices and the result
print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

print("\nResult of matrix multiplication (3x4):")
print(result)

Matrix C (3x2):
[[6 8]
 [5 1]
 [3 3]]

Matrix D (2x4):
[[5 5 3 7]
 [6 9 8 3]]

Result of matrix multiplication (3x4):
[[ 78 102  82  66]
 [ 31  34  23  38]
 [ 33  42  33  30]]


In [34]:
# 83. Create a matrix `E` and find its transpose.
# Create matrix E (3x4) with random integers
E = np.random.randint(1, 11, size=(3, 4))

# Find the transpose of matrix E
E_transpose = E.T

# Print matrix E and its transpose
print("Matrix E (3x4):")
print(E)

print("\nTranspose of Matrix E (4x3):")
print(E_transpose)

Matrix E (3x4):
[[2 2 1 4]
 [1 6 8 6]
 [8 3 9 7]]

Transpose of Matrix E (4x3):
[[2 1 8]
 [2 6 3]
 [1 8 9]
 [4 6 7]]


In [35]:
# 84. Generate a square matrix `F` and compute its determinant.
# Generate a square matrix F (e.g., 3x3) with random integers
F = np.random.randint(1, 11, size=(3, 3))

# Compute the determinant of the matrix F
det_F = np.linalg.det(F)

# Print matrix F and its determinant
print("Matrix F (3x3):")
print(F)

print("\nDeterminant of Matrix F:")
print(det_F)

Matrix F (3x3):
[[4 9 3]
 [9 6 2]
 [5 2 5]]

Determinant of Matrix F:
-247.00000000000006


In [36]:
# 85. Create a square matrix `G` and find its inverse.
# Generate a square matrix G (e.g., 3x3) with random integers
G = np.random.randint(1, 11, size=(3, 3))

# Compute the inverse of matrix G
# Check if the matrix is invertible by ensuring its determinant is non-zero
det_G = np.linalg.det(G)

if det_G != 0:
    inv_G = np.linalg.inv(G)
    print("Matrix G (3x3):")
    print(G)

    print("\nInverse of Matrix G:")
    print(inv_G)
else:
    print("Matrix G is singular and does not have an inverse.")

Matrix G (3x3):
[[ 9  7 10]
 [ 3  1  6]
 [ 1  9  6]]

Inverse of Matrix G:
[[ 0.1875    -0.1875    -0.125    ]
 [ 0.046875  -0.171875   0.09375  ]
 [-0.1015625  0.2890625  0.046875 ]]
